import {Product} from './models/product';
export var PRODUCTS: Product[] = [
    { "id" : 1,
     "name": "Toothbrush",
     "sku": "d",
     "barcode": "f",
     "image": "https://boots.scene7.com/is/image/Boots/10161445?id=PfNaG1&fmt=jpg&fit=constrain,1&wid=504&hei=548",
     "price": 0,
     "rating": 4.6,
     "summary" : "short blah",
     "description": "blah",
     "qtyinstock" : 10,
     "delivertohome" : true,
     "isfeatured" : false,
     "availableinstorenextday" : true},
     { "id" : 2,
      "name": "Bacon",
      "sku": "d",
      "barcode": "f",
      "image": "https://boots.scene7.com/is/image/Boots/10161445?id=PfNaG1&fmt=jpg&fit=constrain,1&wid=504&hei=548",
      "price": 0,
      "rating": 4.6,
      "summary" : "short blah",
      "description": "blah",
      "qtyinstock" : 10,
      "delivertohome" : true,
      "isfeatured" : false,
      "availableinstorenextday" : true},
      { "id" : 3,
       "name": "Cheese",
       "sku": "d",
       "barcode": "f",
       "image": "https://boots.scene7.com/is/image/Boots/10161445?id=PfNaG1&fmt=jpg&fit=constrain,1&wid=504&hei=548",
       "price": 0,
       "rating": 4.6,
       "summary" : "short blah",
       "description": "blah",
       "qtyinstock" : 10,
       "delivertohome" : true,
       "isfeatured" : false,
       "availableinstorenextday" : true},
       { "id" : 4,
        "name": "Cake",
        "sku": "d",
        "barcode": "f",
        "image": "https://boots.scene7.com/is/image/Boots/10161445?id=PfNaG1&fmt=jpg&fit=constrain,1&wid=504&hei=548",
        "price": 0,
        "rating": 4.6,
        "summary" : "short blah",
        "description": "blah",
        "qtyinstock" : 10,
        "delivertohome" : true,
        "isfeatured" : false,
        "availableinstorenextday" : true}
];
